### ISSUE TITLE
Light/shadows leaks

### ISSUE THREAD

**Issue by yurimotilev** [castle-engine/castle-game#2]
In Castle Hall level - light and shadows goes through inner walls when red light turns on.
![castle_screen_0](https://user-images.githubusercontent.com/104770834/166240233-63942e11-b28a-4239-9775-69cb909297eb.png)

Castle Game Engine version: 7.0-alpha.snapshot (unstable) (commit 431215ff3ff1312fe3fd25899c35fc90c32bb80e).
Editor compiled with FPC 3.2.2.
Editor platform: Desktop, OS: Win64, CPU: x86_64 (this exe is using 64-bit architecture).

**Comment by michaliskambi** [comment]
Originally, it was indeed a well-known bug, that is hard to fix with shadow volumes. I documented it here: https://castle-engine.io/vrml_engine_doc/output/xsl/html/section.ghost_shadows.html

Since then, it became a feature :) The point of the werewolves was to be scary and indeed leak through walls.

In new games, I'd solve it by just making the level following reality -- the red light should actually not shine on corridor either. 

So I know now how to fix it, with both shadow volumes and shadow maps, but it would require changing the lighting on this. For this old game, I treat this weird behavior as a feature :)

**Comment by yurimotilev** [comment]
Thanks for explaining, I was discouraged :)

**Comment by michaliskambi** [comment]
A bit related//unrelated note: I just fixed the lighting on castle-game.

Materials and lights in this game's data were prepared for old Gouraud shading, that made sense ~10 years ago, but now CGE defaults to more modern Phong shading. While I could just request Gouraud shading (by adding `RenderOptions.PhongShading := false` to `TGameVideoOptions.RenderOptionsSet`), I decided to quickly update materials/lights to make sense with modern Phong shading.

- Decreased light's ambientIntensity (it is no longer multiplicated by diffuse texture in Phong shading, so it makes a different  effect)

- A bit better water on gate/underneath the menu.

I also fixed the water on the fountain level.
